### ISSUE TITLE
有没有单个CPU的波形显示？

### ISSUE THREAD

**Issue by noahsai** [manateelazycat/deepin-system-monitor#1]
现在貌似只是总CPU的占用情况吧，能显示单个CPU的占用情况吗？另外希望波形和环形的动画是连贯的，而不是绘制一段等一阵再绘制另一段

**Comment by manateelazycat** [comment]
不会有单个的CPU, 现在CPU核数太多，全部绘制出来太乱了没法看。
环形动画是连续的，波形的动画要到最后调

**Comment by noahsai** [comment]
我觉得没单个CPU占用并不好，之前有些人就会出现某个CPU占满，另一个CPU正常的情况，用gnome监视器一看就能直观看出有问题了。

**Comment by noahsai** [comment]
你可以设计成双击CPU的环形就在整个左边显示各个CPU的情况啊。双击又返回原型。

**Comment by manateelazycat** [comment]
经过我非常多次的实验，大部分的CPU曲线都是一致的，导致最后绘制的线全部混淆在一起了。
经过我非常多次的思考，我依然觉得显示总CPU占用意义更大，而且给用户直观的感受。

不同CPU不同的占用率只是技术用户的一种心理暗示，我希望用户更关注右边的具体进程的各项指标的占用率，而不是浪费时间去欣赏像乱麻一样的曲线。
