### ISSUE TITLE
getcmdline(pid_t pid) 的字符串下标越界错误

### ISSUE THREAD

**Issue by duanyao** [manateelazycat/deepin-system-monitor#11]
https://github.com/manateelazycat/deepin-system-monitor/blob/94373bc64483c5fcb1f2ff4a93fd8436bd5089b4/nethogs/src/inode2prog.cpp#L129

```c++
for (size_t idx = 0; idx < (cmdline.length() - 1); idx++) {
    if (cmdline[idx] == 0x00) {
      if (replace_null) {
        cmdline[idx] = ' ';
      }
```
如果 cmdline.length() == 0，因为 cmdline.length() 是无符号的，等效于 idx < max_unsigned_long，会造成越界，导致程序崩溃。

**Comment by duanyao** [comment]
至于 cmdline.length() == 0 的原因，我初步判断是 `read_file()` 造成的：在 `open(filepath, O_RDONLY)` 和 `read_file(fd)` 之间，如果相关的进程退出了，读取 `/proc/<pid>/cmdline` 文件可能会是空的。

https://github.com/manateelazycat/deepin-system-monitor/blob/94373bc64483c5fcb1f2ff4a93fd8436bd5089b4/nethogs/src/inode2prog.cpp#L98

```c++
static std::string read_file(const char *filepath) {
  int fd = open(filepath, O_RDONLY);

  if (fd < 0) {
    std::fprintf(stderr, "Error opening %s: %s\n", filepath,
                 std::strerror(errno));
    std::exit(3);
    return NULL;
  }

  std::string contents = read_file(fd);

  if (close(fd)) {
    std::fprintf(stderr, "Error opening %s: %s\n", filepath,
                 std::strerror(errno));
    std::exit(34);
  }

  return contents;
}
```

上述代码似乎还有个问题：如果 `open(filepath, O_RDONLY)` 失败了，则整个程序就报错退出，这是不合适的。因为目标进程可以在任意时间点退出，所以 `open` 可能因为 ENOENT 而失败，至少这种情形并不是错误。

**Comment by manateelazycat** [comment]
@duanyao 你能否直接写一个修复补丁？我主要没有环境测试。
你那边修复以后，我可以帮你提交一个 patch 到 nethogs 上面去。

当然你自己提交也可以，这几天在忙公司非开发的事情，回复晚了抱歉。 ;)

**Comment by duanyao** [comment]
没问题，这个周末应该可以搞定。

**Comment by manateelazycat** [comment]
@duanyao Thanks

**Comment by manateelazycat** [comment]
@duanyao 我实在无法重现，直接盲修了，你如果还有问题，欢迎随时重新打开这个issue
https://github.com/manateelazycat/deepin-system-monitor/commit/0c076e339f186131f91742c4d470aa7644ddcf5e

**Comment by duanyao** [comment]
@manateelazycat 我已经查出来了。
1. 僵尸进程的 `/proc/pid/cmdline` 可以正常访问，但内容为空，所以如果 `getcmdline(pid)` 调用时该进程刚好是僵尸，就会越界崩溃。
2. 如果在进程存在时（包括僵尸状态）打开 `/proc/pid/cmdline`，在进程消失后读这个 FD，则会得到 ESRCH 错误，导致退出。
3. 如果在进程存在时（包括僵尸状态）读 `/proc/`，在进程消失后打开 `/proc/pid/cmdline`，则会得到 ENOENT 错误，导致退出。

为了重现1，可以大量创建短寿命进程，这样 nethogs 有较大概率探测到一个僵尸状态。例如用以下 node.js 程序：

```js
var child_process = require('child_process');

function run() {
    child_process.exec(
        'curl http://localhost:3000', (error, stdout, stderr) => { }
    );
    setTimeout(run, 10);
}

run();
```

2 和 3 也能重现，但出现几率较低，要多等几分钟才会出现一次。

这是我的修复代码：
https://github.com/raboof/nethogs/pull/151

至于为什么在我的机器上容易遇到这个问题，是因为我用了 systemd-swap 的“动态交换文件”模式，该模式周期性的启动 free 等命令，所以也是大量创建短寿命进程的程序。

P.S. 一个有趣的事实：僵尸进程不是唯一 `/proc/pid/cmdline` 为空的进程。通过传递空的 args 参数给 `execv()`，也可以让进程的 `/proc/pid/cmdline` 为空：

```C
char* args[] = {NULL};
execv(exe_path, args);
```
