### ISSUE TITLE
暗色主题状态下，关于对话框为亮色

### ISSUE THREAD

**Issue by dongfengweixiao** [manateelazycat/deepin-system-monitor#12]
RT。
系统为Arch Linux，不过该问题和系统无关。

**Comment by manateelazycat** [comment]
深度所有软件都是这样设计的，所有的关于对话框和设置对话框永远都是浅色。

**Comment by manateelazycat** [comment]
deepin设计风格如此，避免一片黑

2017-11-24 22:07 GMT+08:00 东风唯笑 <notifications@github.com>:
