### ISSUE TITLE
network monitor  problem

### ISSUE THREAD

**Issue by elswerky** [manateelazycat/deepin-system-monitor#7]
network monitor works only when the deepin system monitor is opened 
if i closed the deepin system moinitor and reopened it 
network monitor start counting from begining 

also  we need to integrate the #nethogs tool in deepin system monitor to show data usage per each app or process

**Comment by manateelazycat** [comment]
@elswerky This issue has fixed by https://github.com/manateelazycat/deepin-system-monitor/commit/46d984c1a9cdb8ad7147baa39526b72058d6ed45
