### ISSUE TITLE
force to end option 

### ISSUE THREAD

**Issue by elswerky** [manateelazycat/deepin-system-monitor#8]
what is the force to end option in deepin system monitor is supposed to do ???

to stop app running from inside system monitor or what ??

it is vague 
is it aimed to stop process which is failed to stop by end process opton or what ??
as if it is aimed for that then i don't see it working well

**Comment by manateelazycat** [comment]
@elswerky Force to end menu item do some feature like xkill, you don't need find process to kill, just click graphics application you want kill
